name: Deploy to Production

on:
  push:
    branches:
      - production  # Runs when pushing to "production" branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/camerooooon/qr-scan-track:latest
          cache-from: type=registry,ref=ghcr.io/camerooooon/qr-scan-track:latest
          cache-to: type=inline

      - name: SSH into Server and Update Container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            docker pull ghcr.io/camerooooon/qr-scan-track:latest
            docker stop qr-scan-track || true
            docker rm qr-scan-track || true
            docker run -d --env-file=.env --name=qr-scan-track -p 3000:3000 -v database:/app/ ghcr.io/camerooooon/qr-scan-track:latest
